[[mirrors]]
name = "mainsail-release"
provider = "command"
upstream = ""
command = "/path-venv/python3 /path/update-version.py --workers 5 --config /path/mainsail-mirror.json"
size_pattern = "Total size is ([0-9\\.]+[KMGTP]?)"
interval = 720

[[mirrors]]
name = "fluidd-release"
provider = "command"
upstream = ""
command = "/path-venv/python3 /path/update-version.py --workers 5 --config /path/fluidd-mirror.json"
size_pattern = "Total size is ([0-9\\.]+[KMGTP]?)"
interval = 720
